### PR TITLE
Feature/restoration

### PR DESCRIPTION
**Pull request by rossettistone**
Hi @michelson!

Pardon the delay in getting back to you, but here's the PR I promised. Let me know what you think, and if there are any changes or additions that you'd like me to make. This is my first major PR on an open source library, and any and all feedback is appreciated.

### CODE REVIEW

**Comment by michelson** [comment]
hi @rossettistone 

awesome additions! the solution looks very nice!
maybe it would be useful that the restore method could work with id's too, like restore_to_id(id), because in scenarios where you have many changes in one day it would be impossible to restore to an specific version.

what do you think?

**Comment by rossettistone** [comment]
That makes total sense to me. I was actually pondering the same addition, but had figured to do it as a separate PR! But no matter, let me add it to this one :-)

**Comment by michelson** [comment]
That's great @rossettistone, looking forward for that feature! thank you!

**Comment by rossettistone** [comment]
Ok, updated and passing on Travis! Want to have another look?

**Comment by michelson** [comment]
Merged! thanks you Mr!

**Comment by rossettistone** [comment]
My pleasure!

**Pull request merged**
